version: "3"
services:
  engecopi:
    image: tomcat:8
    container_name: eng_pedido_transferencia
    ports:
      - "8013:8080"
    environment:
      TZ: "America/Fortaleza"
      EBEAN_PROPS: /etc/ebean.properties
    volumes:
      - ./build/libs/producao-1.0.war:/usr/local/tomcat/webapps/pedidosTransferencia.war
      - ./ebean.properties:/etc/ebean.properties
    restart: always
    networks:
      rede_113:
        ipv4_address: 172.113.1.1
networks:
  rede_113:
    ipam:
      driver: default
      config:
        - subnet: 172.113.0.0/16
